<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-12-29 at 00:43:06.
 */
class SignCertificateTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SignCertificate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SignCertificate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
